version: '3.8'
services:
  master-frontend:
    build:
      context: ./frontend
      args:
        - MODE=master
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - './backend:/app'
    command: npm start

  slave-frontend-1:
    build:
      context: ./frontend
      args:
        - MODE=slave
        - SLAVE_ID=1
    ports:
      - '3100:3000'
    volumes:
      - './frontend:/app'
    command: npm run dev
    depends_on:
      - backend

  slave-frontend-2:
    build:
      context: ./frontend
      args:
        - MODE=slave
        - SLAVE_ID=2
    ports:
      - '3101:3000'
    volumes:
      - './frontend:/app'
    command: npm run dev
    depends_on:
      - backend

  slave-frontend-3:
    build:
      context: ./frontend
      args:
        - MODE=slave
        - SLAVE_ID=3
    ports:
      - '3102:3000'
    volumes:
      - './frontend:/app'
    command: npm run dev
    depends_on:
      - backend
