version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=${BACKEND_URL}
        # - BACKEND_URL=localhost
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - './backend:/app'
    command: npm start

