apiVersion: v1
kind: Service
metadata:
  name: frontend-master-service
spec:
  selector:
    app: frontend-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer