apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-slave-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-slave-1
  template:
    metadata:
      labels:
        app: frontend-slave-1
    spec:
      containers:
      - name: frontend-slave-1
        image: cnlhapp.azurecr.io/cnlh-slave-frontend-1:latest
        env:
        - name: NEXT_PUBLIC_MODE
          value: "slave"
        - name: NEXT_PUBLIC_REACT_APP_SLAVE_ID
          value: "1"
        ports:
        - containerPort: 3000
